name: Update Config

on:
  schedule:
    # 每7天运行一次，UTC时间每周一凌晨2点
    - cron: '0 2 * * 1/7'
  workflow_dispatch: # 允许手动触发

jobs:
  update-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install base58
        
    - name: Run encoding script
      run: python encode_config.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add config.json
        git diff --staged --quiet || git commit -m "Update config.json with Base58 encoded data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.mk }}
  del_runs:
    needs: update-config
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs for remote repo
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.mk }}
          repository: 'vampireisoves/source'
          retain_days: 0
          keep_minimum_runs: 4
